apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ .Values.name }}
    labels:
      app: {{ .Values.name }}
spec:
    replicas: 1
    selector:
      matchLabels:
        app: {{ .Values.name }}
    template:
      metadata:
        labels:
          app: {{ .Values.name }}
      spec:
        containers:
          - name: {{ .Values.name }}
            image: {{ .Values.image.repository }}
            env:
              - name: TOKEN
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.secret }}
                      key: token
            envFrom:
              - configMapRef:
                  name: {{ .Values.config }}

                  
